import java.util.Arrays;
import controlP5.*;
import java.util.*;

public class MorseCode implements Cipher {
  
  String toString(){
    return "Morse Code";
  }
  
  public String encrypt(String s, ControlP5 cp5){
    String answer="";
    String x[]=new String[s.length()];
    for(int i=0;i<s.length();i++){
      x[i]=" ";
      if(s.charAt(i)=='a'||s.charAt(i)=='A'){
        x[i]=".-";
      }
      if(s.charAt(i)=='b'||s.charAt(i)=='B'){
        x[i]="-...";
      }
      if(s.charAt(i)=='c'||s.charAt(i)=='C'){
        x[i]="-.-.";
      }
      if(s.charAt(i)=='d'||s.charAt(i)=='D'){
        x[i]="-..";
      }
      if(s.charAt(i)=='e'||s.charAt(i)=='E'){
        x[i]=".";
      }
      if(s.charAt(i)=='f'||s.charAt(i)=='F'){
        x[i]="..-.";
      }
      if(s.charAt(i)=='g'||s.charAt(i)=='G'){
        x[i]="--.";
      }
      if(s.charAt(i)=='h'||s.charAt(i)=='H'){
        x[i]="....";
      }
      if(s.charAt(i)=='i'||s.charAt(i)=='I'){
        x[i]="..";
      }
      if(s.charAt(i)=='j'||s.charAt(i)=='J'){
        x[i]=".---";
      }
      if(s.charAt(i)=='k'||s.charAt(i)=='K'){
        x[i]="-.-";
      }
      if(s.charAt(i)=='l'||s.charAt(i)=='L'){
        x[i]=".-..";
      }
      if(s.charAt(i)=='m'||s.charAt(i)=='M'){
        x[i]="--";
      }
      if(s.charAt(i)=='n'||s.charAt(i)=='N'){
        x[i]="-. ";
      }
      if(s.charAt(i)=='o'||s.charAt(i)=='O'){
        x[i]="---";
      }
      if(s.charAt(i)=='p'||s.charAt(i)=='P'){
        x[i]=".--.";
      }
      if(s.charAt(i)=='q'||s.charAt(i)=='Q'){
        x[i]="--.-";
      }
      if(s.charAt(i)=='r'||s.charAt(i)=='R'){
        x[i]=".-.";
      }
      if(s.charAt(i)=='s'||s.charAt(i)=='S'){
        x[i]="...";
      }
      if(s.charAt(i)=='t'||s.charAt(i)=='T'){
        x[i]="-";
      }
      if(s.charAt(i)=='u'||s.charAt(i)=='U'){
        x[i]="..-";
      }
      if(s.charAt(i)=='v'||s.charAt(i)=='V'){
        x[i]="...-";
      }
      if(s.charAt(i)=='w'||s.charAt(i)=='W'){
        x[i]=".--";
      }
      if(s.charAt(i)=='x'||s.charAt(i)=='X'){
        x[i]="-..-";
      }
      if(s.charAt(i)=='y'||s.charAt(i)=='Y'){
        x[i]="-.--";
      }
      if(s.charAt(i)=='z'||s.charAt(i)=='Z'){
        x[i]="--..";
      }
      if(s.charAt(i)=='9'){
        x[i]="----.";
      }
      if(s.charAt(i)=='8'){
        x[i]="---..";
      }
      if(s.charAt(i)=='z'||s.charAt(i)=='Z'){
        x[i]="--..";
      }
      if(s.charAt(i)=='7'){
        x[i]="--...";
      }
      if(s.charAt(i)=='6'){
        x[i]="-....";
      }
      if(s.charAt(i)=='5'){
        x[i]=".....";
      }
      if(s.charAt(i)=='4'){
        x[i]="....-";
      }
      if(s.charAt(i)=='3'){
        x[i]="...--";
      }
      if(s.charAt(i)=='2'){
        x[i]="..---";
      }
      if(s.charAt(i)=='1'){
        x[i]=".----";
      }
      if(s.charAt(i)=='0'){
        x[i]="-----";
      }
      if(s.charAt(i)=='.'){
        x[i]=".-.-.-";
      }
      if(s.charAt(i)==','){
        x[i]="--..--";
      }
      if(s.charAt(i)=='?'){
        x[i]="..--..";
      }
      if(s.charAt(i)=='!'){
        x[i]="-.-.--";
      }
      if(s.charAt(i)=='\''){
        x[i]=".----.";
      }
      if(s.charAt(i)=='\"'){
        x[i]=".-..-.";
      }
      if(s.charAt(i)=='('){
        x[i]="-.--.";
      }
      if(s.charAt(i)==')'){
        x[i]="-.--.-";
      }
      if(s.charAt(i)=='&'){
        x[i]=".-...";
      }
      if(s.charAt(i)==':'){
        x[i]="---...";
      }
      if(s.charAt(i)==';'){
        x[i]="-.-.-.";
      }
      if(s.charAt(i)=='/'){
        x[i]="-..-.";
      }
      if(s.charAt(i)=='_'){
        x[i]="..--.-";
      }
      if(s.charAt(i)=='='){
        x[i]="-...-";
      }
      if(s.charAt(i)=='+'){
        x[i]=".-.-.";
      }
      if(s.charAt(i)=='-'){
        x[i]="-...-";
      }
      if(s.charAt(i)=='$'){
        x[i]="...-..-";
      }
      if(s.charAt(i)=='@'){
        x[i]=".--.-.";
      }
      answer+=x[i]+" ";
    }
    return answer.substring(0,answer.length()-1);
  }
  
  public String decrypt(String s, ControlP5 cp5){
    String answer="";
    String x[]=new String[s.length()];
    for(int i=0;i<s.length();i++){
      x[i]=" ";
      if(s.charAt(i)=='a'||s.charAt(i)=='A'){
        x[i]=".-";
      }
      if(s.charAt(i)=='b'||s.charAt(i)=='B'){
        x[i]="-...";
      }
      if(s.charAt(i)=='c'||s.charAt(i)=='C'){
        x[i]="-.-.";
      }
      if(s.charAt(i)=='d'||s.charAt(i)=='D'){
        x[i]="-..";
      }
      if(s.charAt(i)=='e'||s.charAt(i)=='E'){
        x[i]=".";
      }
      if(s.charAt(i)=='f'||s.charAt(i)=='F'){
        x[i]="..-.";
      }
      if(s.charAt(i)=='g'||s.charAt(i)=='G'){
        x[i]="--.";
      }
      if(s.charAt(i)=='h'||s.charAt(i)=='H'){
        x[i]="....";
      }
      if(s.charAt(i)=='i'||s.charAt(i)=='I'){
        x[i]="..";
      }
      if(s.charAt(i)=='j'||s.charAt(i)=='J'){
        x[i]=".---";
      }
      if(s.charAt(i)=='k'||s.charAt(i)=='K'){
        x[i]="-.-";
      }
      if(s.charAt(i)=='l'||s.charAt(i)=='L'){
        x[i]=".-..";
      }
      if(s.charAt(i)=='m'||s.charAt(i)=='M'){
        x[i]="--";
      }
      if(s.charAt(i)=='n'||s.charAt(i)=='N'){
        x[i]="-. ";
      }
      if(s.charAt(i)=='o'||s.charAt(i)=='O'){
        x[i]="---";
      }
      if(s.charAt(i)=='p'||s.charAt(i)=='P'){
        x[i]=".--.";
      }
      if(s.charAt(i)=='q'||s.charAt(i)=='Q'){
        x[i]="--.-";
      }
      if(s.charAt(i)=='r'||s.charAt(i)=='R'){
        x[i]=".-.";
      }
      if(s.charAt(i)=='s'||s.charAt(i)=='S'){
        x[i]="...";
      }
      if(s.charAt(i)=='t'||s.charAt(i)=='T'){
        x[i]="-";
      }
      if(s.charAt(i)=='u'||s.charAt(i)=='U'){
        x[i]="..-";
      }
      if(s.charAt(i)=='v'||s.charAt(i)=='V'){
        x[i]="...-";
      }
      if(s.charAt(i)=='w'||s.charAt(i)=='W'){
        x[i]=".--";
      }
      if(s.charAt(i)=='x'||s.charAt(i)=='X'){
        x[i]="-..-";
      }
      if(s.charAt(i)=='y'||s.charAt(i)=='Y'){
        x[i]="-.--";
      }
      if(s.charAt(i)=='z'||s.charAt(i)=='Z'){
        x[i]="--..";
      }
      if(s.charAt(i)=='9'){
        x[i]="----.";
      }
      if(s.charAt(i)=='8'){
        x[i]="---..";
      }
      if(s.charAt(i)=='z'||s.charAt(i)=='Z'){
        x[i]="--..";
      }
      if(s.charAt(i)=='7'){
        x[i]="--...";
      }
      if(s.charAt(i)=='6'){
        x[i]="-....";
      }
      if(s.charAt(i)=='5'){
        x[i]=".....";
      }
      if(s.charAt(i)=='4'){
        x[i]="....-";
      }
      if(s.charAt(i)=='3'){
        x[i]="...--";
      }
      if(s.charAt(i)=='2'){
        x[i]="..---";
      }
      if(s.charAt(i)=='1'){
        x[i]=".----";
      }
      if(s.charAt(i)=='0'){
        x[i]="-----";
      }
      if(s.charAt(i)=='.'){
        x[i]=".-.-.-";
      }
      if(s.charAt(i)==','){
        x[i]="--..--";
      }
      if(s.charAt(i)=='?'){
        x[i]="..--..";
      }
      if(s.charAt(i)=='!'){
        x[i]="-.-.--";
      }
      if(s.charAt(i)=='\''){
        x[i]=".----.";
      }
      if(s.charAt(i)=='\"'){
        x[i]=".-..-.";
      }
      if(s.charAt(i)=='('){
        x[i]="-.--.";
      }
      if(s.charAt(i)==')'){
        x[i]="-.--.-";
      }
      if(s.charAt(i)=='&'){
        x[i]=".-...";
      }
      if(s.charAt(i)==':'){
        x[i]="---...";
      }
      if(s.charAt(i)==';'){
        x[i]="-.-.-.";
      }
      if(s.charAt(i)=='/'){
        x[i]="-..-.";
      }
      if(s.charAt(i)=='_'){
        x[i]="..--.-";
      }
      if(s.charAt(i)=='='){
        x[i]="-...-";
      }
      if(s.charAt(i)=='+'){
        x[i]=".-.-.";
      }
      if(s.charAt(i)=='-'){
        x[i]="-...-";
      }
      if(s.charAt(i)=='$'){
        x[i]="...-..-";
      }
      if(s.charAt(i)=='@'){
        x[i]=".--.-.";
      }
    }
    answer=StringUtils.join(x," ");
    return answer;
  }
  
}
